chapnewcrud/chapnewcrud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('', include('core.urls')),
]

chapnewcrud/core/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('add/', views.AddView.as_view(), name='add'),
    path('posts/', views.PostsView.as_view(), name='posts'), 
    path('<slug:slug>/', views.SingleView.as_view(), name='single'),
    path('edit/<int:pk>/', views.EditView.as_view(), name='edit'),
    path('delete/<int:pk>/', views.Delete.as_view(), name='delete'),
]
# urls runs from top to bottom

chapnewcrud/core/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User

class Core(models.Model):
    title = models.CharField(max_length=200)
    excerpt = models.TextField(null=True)
    author =models.ForeignKey(User, on_delete=models.CASCADE, related_name='core')
    slug = models.SlugField(max_length=100, unique=True)
    updated = models.DateTimeField(auto_now=True)
    published = models.DateTimeField (default=timezone.now)

    def get_absolute_url(self):
        return reverse('core:single', args=[self.slug])

    class Meta:
        ordering = ['-published']

    def __str__(self):
       return self.title

chapnewcrud/core/forms.py
from django import forms
from .models import Core



class PostForm(forms.ModelForm):
    class Meta:
        Model = Core
        fields = "__all__"

chapnewcrud/core/views.py
from django.shortcuts import render
from .models import Core
from django.views.generic import ListView, DetailView, UpdateView, DeleteView, CreateView
from django.urls import reverse_lazy

# Create your views here.

class IndexView(ListView):
    model = Core
    template_name = 'core/index.html'
    context_object_name = 'index'

class SingleView(DetailView):
    model = Core
    template_name ='core/single.html'
    context_object_name = 'post'

class PostsView(ListView):
    model = Core
    template_name ='core/posts.html'
    context_object_name = 'post_list'

class AddView(CreateView):
    model = Core
    template_name ='core/add.html'
    fields = '__all__'
    success_url = reverse_lazy('core:posts')

class EditView(UpdateView):
    model = Core
    template_name ='core/edit.html'
    fields = '__all__'
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('core:posts')

class Delete(DeleteView):
    model = Core
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('core:posts')
    template_name ='core/confirm-delete.html'


chapnewcrud/core/templates/core/add.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}
{% block content %}

<div class="container pt-5">
    <form method="post" novalidate>
        {% csrf_token %}
        {% for field in form.visible_fields %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field|add_class:'form-control'}}
            {% for error in field.errors %}
            <span class="help-block">{{ error }}</span>
            {% endfor %}
        </div>
        {% endfor %}
        <div class="form-group">
            <button type="submit" class="btn btn-success">
                <span class="glyphicon glyphicon-ok"></span>Edit
            </button>
            <a href="{% url 'core:posts' %} " class="btn btn-defult">Cancel</a>
        </div>
    </form>
</div>

{% endblock %}

chapnewcrud/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
</head>
<body>
    {% include 'core/navbar.html' %}

    {% block content %}

    {% endblock %}
    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

    {% include 'core/footer.html' %}
</body>
</html>

chapnewcrud/core/templates/core/confirm-delete.html
{% extends 'core/base.html' %}
{% block content %}

<div class="container pt-5">
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm">
    </form>
</div>

{% endblock %}

chapnewcrud/core/templates/core/edit.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}
{% block content %}

<div class="container pt-5">
    <form method="post" novalidate>
        {% csrf_token %}
        {% for field in form.visible_fields %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field|add_class:'form-control'}}
            {% for error in field.errors %}
            <span class="help-block">{{ error }}</span>
            {% endfor %}
        </div>
        {% endfor %}
        <div class="form-group">
            <button type="submit" class="btn btn-success">
                <span class="glyphicon glyphicon-ok"></span>Edit
            </button>
            <a href="{% url 'core:posts' %} " class="btn btn-defult">Cancel</a>
        </div>
    </form>
</div>

{% endblock %}

chapnewcrud/core/templates/core/footer.html
<div class="conatiner">
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                CMS Primer
                <small class="d-block mb-3 text-muted">Crud Operation</small>
            </div>
            <div class="col-6 col-md">
                <h5>Admin</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted">Post Admin</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>About Us</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted">Home</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Resources</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted">Single code resources</a></li>
                    <li><a class="text-muted">Youtube Link</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

chapnewcrud/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block content %}

<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            {% for core in index %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-image-top" src="https://via.placeholder.com/150x100" alt="card image">
                    <div class="card-body">
                        <h4 class=""><a href="{{ core.get_absolute_url }}">{{ core.title }}</a></h4>
                        <p class="card-test"></p>
                        <div class="d flex justify-content-between align-items-center">
                            <div class="">
                                <small class="text-muted">9 mins</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

chapnewcrud/core/templates/core/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand d-flex align-items-center" href="#">
        <img src="core\static\img\image1.svg" width="70" height="40" alt="">
      </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'core:posts' %}">Home</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'core:posts' %}">Manage Posts</a>
        </li>
      </ul>
    </div>
  </nav>

chapnewcrud/core/templates/core/post-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>

chapnewcrud/core/templates/core/posts.html
{% extends 'core/base.html' %}

{% block content %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="navbar-brand"> Post Administration </div>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'core:add' %}">Add New</a>
            </li>
        </ul>
    </div>
</nav>

<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            {% for post in post_list %}
            <div class="col-md-4">
                <div class="card md-4 box-shadow">
                    <img class="card-img-top" src="https://via.placeholder.com/150x100" alt="Card img">
                    <div class="card-body">
                        <h4 class="lead"><a class="text-dark" href="{% url 'core:single' post.pk %}">{{ post.title }}</a></h4>
                        <p class="card-text"></p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{{ post.get_absolute_url }}" class="btn btn-sn btn-outline-primary" role="button" aria-pressed="true">View</a>
                                <a href="{% url 'core:edit' post.pk %}" class="btn btn-sn btn-outline-primary" role="button" aria-pressed="true">Edit</a>
                                <a href="{% url 'core:delete' post.pk %}" class="btn btn-sn btn-outline-primary" role="button" aria-pressed="true">Delete</a>
                            </div>
                            <small class="text-muted">9 mins</small>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

chapnewcrud/core/templates/core/single.html
{% extends 'core/base.html' %}

{% block content %}


    <div class="container">
        <div class="row">
            <div class="col-12 pt-5">
                <img class="card-image-top" src="https://via.placeholder.com/300x100" alt="card image">
                    <h2 class="pt-5">{{ post.title }}</h2>
                    <p>{{post.excerpt}}</p>             
            </div>
        </div>
    </div>


{% endblock %}